services:
    app:
        build: .
        container_name: jaba
        volumes:
            - ./config.json:/root/app/config.json
        environment:
            NODE_ENV: production
        depends_on:
            - mongo
    mongo:
        image: mongo:8
        container_name: mongo
        # ports:
        #     - 27017:27017
        volumes:
            - mongo_data:/data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost --quiet
            interval: 30s
            timeout: 10s

volumes:
    mongo_data: