version: "3.9"

services:
    app:
      build: .
      container_name: jaba
      volumes:
          - .:/app
          - /app/node_modules
          - ./config.json:/app/config.json
      environment:
          NODE_ENV: production
          MONGO_URI: mongodb://mongo:27017/jaba_db
      depends_on:
          - mongo

    mongo:
      image: mongo:latest
      container_name: jaba_mongo
      ports:
          - "27017:27017"
      volumes:
          - mongo_data:/data/db

volumes:
    mongo_data:
