name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        run: |
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "**Docker image**: https://github.com/${{ github.repository }}/pkgs/container/jaba" >> RELEASE_NOTES.md
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: RELEASE_NOTES.md
          draft: true
          prerelease: false